### ISSUE TITLE
Please add proxy support

### ISSUE THREAD

**Issue by sital33** [akamai/NetStorageKit-Java#5]
Please add support for a configurable proxy. I've changed my local code to use a hard-coded proxy, but it would be good to have an option to pass it in via a constructor.

**Comment by amareen1988** [comment]
+1

**Comment by colinbendell** [comment]
You should be able to set the system properties to force HttpUrlConnection to use the proxy. For example:
```java
System.setProperty("https.proxyHost","localhost");
System.setProperty("https.proxyPort","8080");
```
Or on the command line:
```sh
java -cp classes -Dhttps.proxyHost=localhost -Dhttps.proxyPort=8080 com.akamai.netstorage.cli.CMS -a dir /
```

**Comment by colinbendell** [comment]
Does this not work for you?

**Comment by dshafik** [comment]
@sital33 @amareen1988 were you able to try and verify @colinbendell's suggestion? I'd like to close this ticket if so…

**Comment by vladonemo** [comment]
I was able to test this by setting the system properties. The issue can be closed.

**Comment by dshafik** [comment]
@vladonemo thanks for the information!
